# Generated by Django 5.1.15 on 2026-03-15 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('enabled', models.BooleanField(db_comment='should be visible to user as separate catory tab')),
                ('order', models.IntegerField(blank=True, db_comment='app order', null=True)),
                ('live_feed_type', models.IntegerField(db_comment='0=not live feed, 1+=live feed type ID', default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Divisions',
                'db_table': 'divisions',
            },
        ),
        migrations.CreateModel(
            name='Sourcealias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.TextField(unique=True)),
                ('alias', models.TextField()),
                ('alias_en', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Source Aliases',
                'db_table': 'sourceAlias',
            },
        ),
        migrations.CreateModel(
            name='Timelines',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('title', models.TextField(blank=True, null=True)),
                ('newslist', models.TextField(blank=True, db_column='newsList', null=True)),
                ('imgurl', models.TextField(blank=True, db_column='imgUrl', null=True)),
                ('isnew', models.BooleanField(blank=True, db_column='isNew', null=True)),
            ],
            options={
                'verbose_name_plural': 'Timelines',
                'db_table': 'timelines',
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('order', models.IntegerField()),
                ('enabled', models.BooleanField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Topics',
                'db_table': 'topics',
            },
        ),
        migrations.CreateModel(
            name='Videopublishers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(unique=True)),
                ('url', models.TextField(unique=True)),
                ('profileiconurl', models.TextField(blank=True, db_column='profileIconUrl', null=True)),
                ('platform', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Video publishers',
                'db_table': 'videoPublishers',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('summary', models.TextField()),
                ('source', models.CharField(db_comment='source url', max_length=255, unique=True)),
                ('imageurl', models.TextField(blank=True, db_column='imageUrl', null=True)),
                ('timestamp', models.DateTimeField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('categoryid', models.ForeignKey(blank=True, db_column='categoryId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.categories')),
                ('divisionid', models.ForeignKey(blank=True, db_column='divisionId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.divisions')),
                ('topic', models.ForeignKey(blank=True, db_column='topic', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.topics')),
            ],
            options={
                'verbose_name_plural': 'News',
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='Extradetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('original_news', models.TextField()),
                ('card', models.TextField(blank=True, null=True, unique=True)),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.news')),
            ],
            options={
                'verbose_name_plural': 'Extra Details',
                'db_table': 'extraDetails',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('videourl', models.TextField(blank=True, db_column='videoUrl', null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('thumbnailurl', models.TextField(blank=True, db_column='thumbnailUrl', db_comment='thumbnailUrl', null=True)),
                ('publisher', models.ForeignKey(blank=True, db_column='publisher', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.videopublishers')),
            ],
            options={
                'verbose_name_plural': 'Videos',
                'db_table': 'videos',
            },
        ),
    ]
