# Generated by Django 5.1.15 on 2026-03-15 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='publisher',
            field=models.ForeignKey(blank=True, db_column='publisher', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.videopublishers'),
        ),
    ]
