# Generated by Django 5.1.15 on 2026-04-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_add_category_config_and_published_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='name_en',
            field=models.TextField(blank=True, default=''),
        ),
    ]
