# Generated by Django 5.1.15 on 2026-09-27 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_livefeedhub_and_publish_dedupe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.TextField(unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=16)),
                ('provider', models.CharField(choices=[('fcm', 'FCM'), ('apns', 'APNs')], max_length=16)),
                ('environment', models.CharField(choices=[('production', 'Production'), ('sandbox', 'Sandbox')], default='production', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('locale', models.CharField(default='bn', max_length=8)),
                ('app_version', models.CharField(blank=True, default='', max_length=32)),
                ('last_error', models.CharField(blank=True, default='', max_length=64)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'push_devices',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['platform', 'enabled', 'environment'], name='push_dev_send_idx'), models.Index(fields=['invalidated_at'], name='push_dev_invalidated_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('news', 'Existing news'), ('custom', 'Custom message')], default='news', max_length=16)),
                ('title', models.CharField(blank=True, help_text='Keep under ~65 characters to avoid truncation.', max_length=120)),
                ('body', models.CharField(blank=True, help_text='Keep under ~180 characters to avoid truncation.', max_length=300)),
                ('image_url', models.URLField(blank=True, default='', help_text='HTTPS JPEG/PNG/GIF, a few hundred KB at most.', max_length=1000)),
                ('target', models.CharField(choices=[('all', 'Android & iOS'), ('android', 'Android'), ('ios', 'iOS')], default='all', max_length=16)),
                ('topic', models.CharField(default='breaking_news', max_length=64)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('partial', 'Partially sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=16)),
                ('origin', models.CharField(choices=[('portal', 'Portal'), ('api', 'API')], default='portal', max_length=16)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, help_text='Leave empty to send immediately.', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('fcm_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('fcm_error', models.TextField(blank=True, default='')),
                ('ios_sent', models.PositiveIntegerField(default=0)),
                ('ios_failed', models.PositiveIntegerField(default=0)),
                ('ios_invalidated', models.PositiveIntegerField(default=0)),
                ('ios_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_notifications', to='data.news')),
            ],
            options={
                'db_table': 'push_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='push_notif_due_idx')],
            },
        ),
    ]
