# Generated by Django 5.1.15 on 2026-10-02 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_push_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchReindexJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('cancelling', 'Cancelling'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=16)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('deploy', 'Deploy'), ('nightly', 'Nightly')], default='manual', max_length=16)),
                ('total', models.PositiveIntegerField(default=0)),
                ('indexed', models.PositiveIntegerField(default=0)),
                ('removed', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search reindex',
                'verbose_name_plural': 'Search reindex',
                'db_table': 'search_reindex_jobs',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='search_reindex_single_active')],
            },
        ),
    ]
