services:
  db:
    ports:
      - "5432:5432"

  django:
    build:
      context: .
      args:
        INSTALL_DEV: "true"
    env_file: .env
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - CSRF_TRUSTED_ORIGINS=*
    ports:
      - "8000:8000"
